### ISSUE TITLE
Custom CSS lacks documentation, set CSS-classes?

### ISSUE THREAD

**Issue by florhizome** [WayfireWM/wf-shell#101]
I tried customizing wf-panel and wf-dock via css, esp concerning the issue that is described in #35. Right now this is not very sufficient, since:
- there is no documentation or an example file on the feature
This is especially crucial, since it's not clear to me how to declare rules on a single widget/ object class. In similar projects like waybar/nwg-launchers widgets have own CSS ID-s so their style can easily manipulated, and they could be declared in the config file by the user himself. While I don't know if that's already possible,  it certainly isn't documented anywhere Empowering CSS styling would enable ppl to do a lot more by themselves without maintainers having to merge new features. Right now there are already  many options that are quite redundant with CSS rules funcionalities, and more are requested - if those styling requests aren't of high importance to you rn, you can save time here :)

**Comment by ammen99** [comment]
Honestly, I have never used this feature. Maybe ask the original author how they are customizing :)

Having IDs will probably be useful, we should set these programatically. As a wild guess, you may use GTK_DEBUG=interactive to see what widgets are there.

**Comment by florhizome** [comment]
yeah that's what i did ;) They are there - the panel is a window, the widgets mostly consist out of boxes buttons and Labels/Iimages. But without IDs  it's hard to target them. this would be even more important if the pull for more flexible custom buttons is merged.

**Comment by NamorNiradnug** [comment]
Fixed in #239, #241, etc.
