### ISSUE TITLE
Add a way to open the menu widget from the terminal

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wf-shell#11]
This way we can bind such a command to a keybinding and open the menu with it.

**Comment by soreau** [comment]
dbus comes to mind, though I find the syntax unwelcoming (both the API code and dbus-send).

**Comment by AdrianVovk** [comment]
D-Bus is a fair choice for IPC. It's cross-platform (so the BSD port can use it), it's extremely cross-language, and it is stable. I can be a bit clunky in the c/c++ world, but it gets the job done, and works with many debug tools.

@soreau, if you don't like dbus-send, you can use busctl (if you use a systemd-based distro)

**Comment by ammen99** [comment]
What I find problematic is the case where we have multiple outputs (or even multiple Wayfire's running). How does the command know which instance to send it to? Perhaps we should just do a Wayfire plugin for tight integration with wf-shell.

**Comment by soreau** [comment]
@ammen99 With compiz there is a concept of screens for each call so the dbus-send caller would choose screen[n] for different instances or allscreens where it doesn't matter. (See [the wiki](http://wiki.compiz.org/Plugins/Dbus) for examples) For knowing which output, you could probably also build it into the call or just use the focused one.

**Comment by myfreeweb** [comment]
In numbernine currently I have a launcher that just [pops up as a layer-shell surface on an unspecified output](https://github.com/myfreeweb/numbernine/blob/2d1ddee121e1aa8bbb4affe9d5f79776014c3070/launcher/main.cpp#L137-L145) when a gtk action is called, and a panel button that [just calls a gtk action over dbus](https://github.com/myfreeweb/numbernine/blob/2d1ddee121e1aa8bbb4affe9d5f79776014c3070/panel/widgets/remoteaction.cpp). Absolutely no explicit mention of outputs anywhere, Wayfire just puts the lsh surface on the focused output, which is where the button was clicked :)

> multiple Wayfire's running

Each instance should have its own session bus.

> clunky in the c/c++ world

[gdbus-codegen-glibmm](https://github.com/Pelagicore/gdbus-codegen-glibmm) is awesome :) (but with gtk actions, you don't need anything like that)
