### ISSUE TITLE
[wf-panel] Start-menu: Allow to select/launch items via keyboard

### ISSUE THREAD

**Issue by Nuc1eoN** [WayfireWM/wf-shell#111]
Often times I type in a search term, and then instinctively use my `down` key to select the item and launch it with `enter`.

But it seems that is not implemented.

My proposed idea is, that the first item should always be auto selected by default, and the user can use his arrow keys to change the selected item.

The second option is, that the user first needs to press the down arrow to enter the item list. (But frankly I don't think that extra step is of any use for the user.)

**Comment by ammen99** [comment]
fixed in #230
