### ISSUE TITLE
Inconsistency in naming

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wf-shell#122]
Maybe I've got confused but

I'm now running `wf-panel` which reads its conf from `$HOME/.config/wf-shell.ini`

However the project is called `wf-shell` despite the binary name.

Please make it consistent.

**Comment by ammen99** [comment]
wf-shell.ini is used by both the panel and the background, unsure how you want to call the config file?

**Comment by birdie-github** [comment]
Rename `wf-panel` to `wf-shell`? I don't know to be honest.
