### ISSUE TITLE
windows-list: icon missing because of `app_id`

### ISSUE THREAD

**Issue by starsareintherose** [WayfireWM/wf-shell#129]
Hello

I can set the launcher icon seems normal, but for window-list, it always missing icon, because the `app_id` and name do not match, I guess.

for example, newsflash
```
View ID: 1404722472
App ID: NewsFlashGTK
Title: NewsFlash
Role: TOPLEVEL
Geometry: 360,239 1200x650
```

So what solution or what code should I help with?

**Comment by starsareintherose** [comment]
from matrix
```
kuoi: The code to lookup the icons for window-list is here
https://github.com/WayfireWM/wf-shell/blob/master/src/panel/widgets/window-list/toplevel.cpp#L594-L674
```
try to fix it later

**Comment by ammen99** [comment]
That's a client bug, an application's app-id must always match their .desktop file. We have support for setting custom icons for specific app-id's to work around this, but of course fixing the app if possible is a better way to fix it.


https://github.com/WayfireWM/wf-shell/blob/8caa6a05e4e646af3bd16a470fefbf3639096d93/wf-shell.ini.example#L129

This should work in the panel section too (not just the dock)

**Comment by wb9688** [comment]
They call `set_prgname` with `NewsFlashGTK` as argument at https://gitlab.com/news-flash/news_flash_gtk/-/blob/master/src/main.rs#L114 while their desktop file is called `org.gitlab.newsflash.desktop`. If they fix the before mentioned line of code to have `org.gitlab.newsflash` it would work, and as they're using GTK 4 it is kinda important to set it correctly.

**Comment by starsareintherose** [comment]
> That's a client bug, an application's app-id must always match their .desktop file. We have support for setting custom icons for specific app-id's to work around this, but of course fixing the app if possible is a better way to fix it.
> 
> https://github.com/WayfireWM/wf-shell/blob/8caa6a05e4e646af3bd16a470fefbf3639096d93/wf-shell.ini.example#L129
> 
> This should work in the panel section too (not just the dock)

Okay, I thought it can't be customed under panel and what is it mean
```
icon_mapping_<app-id?> = just png? or png/svg?
```
I am not sure if it's app_id

**Comment by starsareintherose** [comment]
It also depends on theme and svg file may be not displayed.

as https://github.com/WayfireWM/wf-shell/issues/93 said, icon is only found in a specific theme, it won't be shown if the theme is not the specific theme.
