### ISSUE TITLE
[Bug] >-Hotkey event<-  No sound level indicator changes dislayed -- [Fullscreen-windows] --

### ISSUE THREAD

**Issue by Nonie689** [WayfireWM/wf-shell#146]
No Sound level indicator wil display, when I changing the sound level [via shortcut].

On fullscreen videos or windows!

This error is on all programms with fullscreen modes and F11 pseodo fullscreens too.

Testet on:
Opera, Firefox and gedit and more.-

**Comment by NamorNiradnug** [comment]
That's because fullscreen windows are shown "above" the wf-panel
Try to set `layer` option to `overlay`

**Comment by Nonie689** [comment]
Thank you!! 

This solved this issue!


//Bug closed//
