### ISSUE TITLE
command-output doesnt work if output contains an "&"

### ISSUE THREAD

**Issue by mrsteve0924** [WayfireWM/wf-shell#176]
commands like echo "m&ms" will not show output.

cat <path to file> will not work either if contents of file contains an "&"

**Comment by NamorNiradnug** [comment]
Hi. It doesn't work because `&` character is a part Pango Markup and therefore "m&ms" is an invalid text. Use "&amp;" instead.

**Comment by mrsteve0924** [comment]
yep that was it.  a simple `sed` command took care of that.  thanks!
