### ISSUE TITLE
Dependency wf-config found: NO 

### ISSUE THREAD

**Issue by happysmash27** [WayfireWM/wf-shell#18]
Workaround: set PKG_CONFIG_PATH to /usr/local/lib64/pkgconfig/ after installing wf-config. For some reason, it doesn't do this by default.

**Comment by ammen99** [comment]
This isn't our bug. Meson installs things to `/usr/loca/` by default, but pkgconfig doesn't seem to search there.

To make things easier, I usually just install with a prefix `/usr/`
