### ISSUE TITLE
dock can't show up after it hides

### ISSUE THREAD

**Issue by ssfdust** [WayfireWM/wf-shell#184]
### reproduce steps
1. Enable the `autohide` option in dock section of `wf-shell.ini`
2. Start `wf-dock` and wait for the dock to hide
3. Try to hover on the dock edge, it can't show up

**Comment by marcusbritanicus** [comment]
I cannot reproduce this with `0.8.0-95ce6ddf (Oct  1 2023, branch 'master')`

**Comment by soreau** [comment]
I can reproduce on track-wlroots branch, which is rebased on master 489f7a4e. This also affects wf-panel the same way.

**Comment by soreau** [comment]
As @marcusbritanicus pointed out on irc, this is because it requires wayfire-shell plugin to work.

**Comment by ssfdust** [comment]
yes, with the wayfire-shell plugin enable, it works.
