### ISSUE TITLE
wf-dock does not show icons for existing views

### ISSUE THREAD

**Issue by marcusbritanicus** [WayfireWM/wf-shell#185]
Steps to reproduce:
1. Ensure wayfire-shell and foregin-toplevel are enabled in the plugin list
2. Open a few views
3. Open wf-dock
4. wf-dock does not show the existing views
5. Open a new view. wf-dock shows icon for this newly opened view.

Expected behaviour:
wf=dock should show icons for views which were already open

**Comment by lavender-agatha** [comment]
It works fine for me.

Could you please detail which applications are you running for those views?

Could you please provide an screenshot including the `wf-panel` on it? (I'm wondering if the views missing on `wf-dock` for you are appearing on `wf-panel`, and how)

**Comment by soreau** [comment]
This works for me too. When I load wf-dock, all the views' icons are there.
