### ISSUE TITLE
window-list is missing completely

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wf-shell#191]
I don't see running applications :-(

```
widgets_left = spacing4 menu spacing18 launchers spacing18 window-list
widgets_right = notifications spacing18 network battery volume clock
```

Using
```
wf-shell-0.8.0-1.fc38.x86_64
wf-config-0.8.0-1.fc38.x86_64
wayfire-config-manager-0.8.0-1.fc38.x86_64
wayfire-0.8.0-2.fc38.x86_64
```

**Comment by wb9688** [comment]
Is the foreign-toplevel plugin enabled in Wayfire?

**Comment by birdie-github** [comment]
> Is the foreign-toplevel plugin enabled in Wayfire?

Let me check, I've yet to open WayFire settings. Using 0.7's config file as is.

**Comment by birdie-github** [comment]
Added it, the issue is gone. This required me to restart wayfire.
