### ISSUE TITLE
command-output font/size/color

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wf-shell#193]
Would be great if it was possible to configure:

* Font
* Font size
* Font color

for commands.

**Comment by ammen99** [comment]
I wonder whether we could do this somehow via the CSS theming support, we'd probably need to set the proper IDs for the commands, and then use an appropriate CSS selector.

**Comment by NamorNiradnug** [comment]
All the thing can be configured with Pango markup:
```
command_example = echo '<span foreground="blue" size="x-large">Blue text</span> is <i>cool</i>!'
```

**Comment by birdie-github** [comment]
> All the thing can be configured with Pango markup:

@NamorNiradnug 

Please mention this somewhere, a sample ini file or/and Wiki.
