### ISSUE TITLE
Regression: composer allocating windows in the wf-panel's area

### ISSUE THREAD

**Issue by lavender-agatha** [WayfireWM/wf-shell#198]
Since the latest release of wf-shell, I am experiencing an issue with my composer (wayfire).

Whenever I maximize a window or dock it using the grid plugin, the composer seems to be including the wf-panel's area into the area where it puts the window, hiding part of the window.

I checked this behavior and it's not only happening in the latest release, but also in the git version. 

So I bisected it and found out this regression was introduced in 665263593350fddd92322e553fc09895cdebf209, as it changes the auto-hiding code and I found out that it works just fine in the previous commit 0fb7f50d41856a5ee3668286b7362cdb50528b5e. In the end I'm adding two small videos showing the behavior in both cases.

I tested it with both my current config file, the example config file, etc. I have auto-hiding disabled.

I am reading the code to try to understand it and work on a fix.

Here are the videos demonstrating the behaviors:

Behavior in 665263593350fddd92322e553fc09895cdebf209:
https://github.com/WayfireWM/wf-shell/assets/24969130/5761faf1-a142-4b09-b30d-303ffdbcf8ec

Behavior in 0fb7f50d41856a5ee3668286b7362cdb50528b5e:
https://github.com/WayfireWM/wf-shell/assets/24969130/c386601f-6a2a-4cab-bf27-e302377326c1

**Comment by lavender-agatha** [comment]
Important detail: this bug only happens when the shell plugin isn't loaded.

Yet, it's still an unnecessary dependency that could affect wf-shell users running a different compositor.

I'm making a PR to fix it.

**Comment by ammen99** [comment]
fixed in #199
