### ISSUE TITLE
[wf-background] crash if background image path contains parentheses

### ISSUE THREAD

**Issue by dkondor** [WayfireWM/wf-shell#203]
Hi,
I tried setting my background to the following:
```
[background]
cycle_timeout = 150
image = /usr/share/backgrounds/Ross_Jones_Rockpool_(Sydney)_by_Chris_Carignan.jpg
preserve_aspect = true
randomize = false
```
and got wf-background crashing (immediately and also when trying to start it manually).

I looked into this and the crash happens [here](https://github.com/WayfireWM/wf-shell/blob/f0574575bb7675740903bb0e95aefb0144929987/src/background/background.cpp#L129) -- apparently, the variable `exp` is filled with garbage.

I would say that this is actually a bug in `wordexp()`, but it is not entirely clear: [here](https://man7.org/linux/man-pages/man3/wordexp.3.html) it says that "the string must not contain [...] unescaped (, ) characters", which could imply UB, but if I interpret it correctly, the [standard](https://pubs.opengroup.org/onlinepubs/9699919799/functions/wordexp.html) says that in this case "wordexp() shall fail, and the number of expanded words shall be 0" which is not the case on my system (I get we_wordc = 4). However, it would be nice to avoid crashing in this case though.

**Comment by dkondor** [comment]
The following fixes it:

```
diff --git a/src/background/background.cpp b/src/background/background.cpp
index f845447..998fb88 100644
--- a/src/background/background.cpp
+++ b/src/background/background.cpp
@@ -118,6 +118,7 @@ bool WayfireBackground::change_background(int timer)
 bool WayfireBackground::load_images_from_dir(std::string path)
 {
     wordexp_t exp;
+    exp = {};
 
     /* Expand path */
     wordexp(path.c_str(), &exp, 0);
```

It seems that `exp` is initialized with random garbage, and `wordexp()` does not change it if it encounters an error. I'm not sure if that is correct behavior though or if I should try to report this as a bug.

**Comment by soreau** [comment]
> It seems that `exp` is initialized with random garbage, and `wordexp()` does not change it if it encounters an error. I'm not sure if that is correct behavior though or if I should try to report this as a bug.

I would say make a PR with your patch here, even if the bug is with wordexp, it would take awhile to get fixed in distro repos, if a fix is accepted.
