### ISSUE TITLE
Large ethernet Text

### ISSUE THREAD

**Issue by gimpcheesestick** [WayfireWM/wf-shell#21]
It would be awesome to be able to adjsut the font size of the Ethernet notification. Mine is currently 4 inches large. I like the clock being large
![ethernet-panel-text](https://user-images.githubusercontent.com/54387115/63484743-babe6f80-c46e-11e9-88fb-4a11f71fa83c.png)

**Comment by ammen99** [comment]
Doesn't setting the network widget font work?

**Comment by ammen99** [comment]
https://github.com/WayfireWM/wf-shell/blob/master/wf-shell.ini.example#L101

**Comment by gimpcheesestick** [comment]
I apologize, Yes, I was looking for like font_size or something and conpletely overlooked the "style=Book 14" changing Book size did exactly that, thank you!
