### ISSUE TITLE
[Feature] Add panel separator as a widget

### ISSUE THREAD

**Issue by mrsteve0924** [WayfireWM/wf-shell#211]
I use xfce and they have a panel plugin to add a visual separator. 

I kind of hacked one together using launcher_cmd and launcher_icon in wf-shell.ini.  But it's limited to where I can place it.

> launcher_cmd_separator2 = 
launcher_icon_separator2 = /usr/share/icons/Papirus/symbolic/apps/separator-symbolic.svg
![wf-panel](https://github.com/WayfireWM/wf-shell/assets/37476191/eb49a09f-8c8a-48e5-9c57-1ae502f0c6f4)

here's how the separators look on my xfce panel
![xfce-panel](https://github.com/WayfireWM/wf-shell/assets/37476191/ab108645-2e59-4f33-aab0-86690f2df833)

https://docs.xfce.org/xfce/xfce4-panel/separator

**Comment by ammen99** [comment]
fixed in #233, you can use `separator<width in pixels>` just like `spacing` in the config file.
