### ISSUE TITLE
make window-list height resizeable

### ISSUE THREAD

**Issue by whatamesss** [WayfireWM/wf-shell#213]
window-list seems to hold the panel height at a very high number of pixels, only way to get the panel size down currently is to remove the window-list. please add a config option to set the window-list height

**Comment by trigg** [comment]
You should now (if installing latest git version) be able to customise the panel  style even more to your liking.

One option is [Remove all padding](https://github.com/WayfireWM/wf-shell/wiki/Style:-overview#remove-all-padding)

**Comment by soreau** [comment]
It sounds like you want [this commit](https://github.com/WayfireWM/wf-shell/commit/6779db405b2fd684587a41284c030dc3ba0de652). With it, you should be able to set the size by adjusting `panel/minimal_height` option.

**Comment by whatamesss** [comment]
works! looks great!
