### ISSUE TITLE
Windows doesn't go to right position when minimizing 

### ISSUE THREAD

**Issue by zp3x** [WayfireWM/wf-shell#217]
**Description**
When a window is minimized, it does not go to the correct position in WF panel when the window-list is at widgets_center

**To Reproduce**
- Configure in wf-shell.ini
  - widgets_center = window-list

```
[panel]

css_path = .config/css/dock.css
position = bottom


widgets_left = launchers
widgets_center = window-list
widgets_right = tray clock volume


launcher_discord = discord.desktop
launcher_librewolf = io.gitlab.librewolf-community.desktop
launcher_intellij = com.jetbrains.IntelliJ-IDEA-Ultimate.desktop 
launcher_remmina = org.remmina.Remmina.desktop
launcher_filezilla = filezilla.desktop

launchers_animation_duration = 100
launchers_spacing = 10
```

**Expected behavior**
The windows should go in the right place

**Screenshots or stacktrace**
[https://0x0.st/HdOa.mkv](url)

**Wayfire version**
0.8.0

**Comment by ammen99** [comment]
Try this patch: https://0x0.st/Hdwb.diff

**Comment by ammen99** [comment]
@zp3x so the patch works or what? :)

**Comment by zp3x** [comment]
Yes thank you

**Comment by ammen99** [comment]
Reopening until I get back home to merge the patch, otherwise I might forget :)
