### ISSUE TITLE
printf only partially works on command_output

### ISSUE THREAD

**Issue by trames57** [WayfireWM/wf-shell#221]
I am trying to use printf for command_output. I cannot use a space either in the first argument or the second argument. When I do, the output either is blank or only shows the text up to the space.

Example:
```
command_output_test = printf "%s" "Hi there"
command_output_icon_test =
```
The output will be "Hi" instead of "Hi there"

```
command_output_test = printf " %s" "Hi"  (space before %s)
command_output_icon_test =
```
The output is blank.
Also blank if I put a space like this `printf "%s there" "Hi"  (space after %s)
`

I have commands_output_max_chars = 15

**Comment by NamorNiradnug** [comment]
That's because the command is actually run like this: `/bin/sh -c "<command>"`. Try using `'` instead of `"` for quotes.

**Comment by trames57** [comment]
Thanks, that worked.  I thought I had tried that!

**Comment by trames57** [comment]
Closing.
