### ISSUE TITLE
Pressing super key for workspace overview opens menu on every workspace

### ISSUE THREAD

**Issue by trames57** [WayfireWM/wf-shell#222]
I just installed 0.8.1 of wayfire and wf-shell. 0.8.0 of wf-config. In the Arch AUR these are dated 03/14/2024

When I press on the super key and the workspace overview displays (in expo) the menu is opened on every workspace like it was clicked. When I go to a workspace I have to click it closed. When pressing super again, sometimes it opens again, and sometimes it doesn't. On the previous release, this did not happen.  I have disabled the menu widget for the time being since I mostly use wofi.

I am not sure if this is a wayfire issue or wf-shell issue.

**Comment by ammen99** [comment]
Hi, this is a new feature, controlled by the wayfire-shell plugin in Wayfire. You can set the option `wayfire-shell/toggle_menu` to disabled if you don't want to trigger the menu when super is pressed, or configure another key.
