### ISSUE TITLE
panel crashes if problems with icons

### ISSUE THREAD

**Issue by mrsteve0924** [WayfireWM/wf-shell#224]
kept getting this error when launching wf-panel:

> (wf-panel:38012): Gtk-WARNING **: 11:56:53.179: Could not load a pixbuf from icon theme.
> This may indicate that pixbuf loaders or the mime database could not be found.
> terminate called after throwing an instance of 'Gio::Error'
> Aborted (core dumped)

i was able to fix this by repairing the icon-theme.cache with `gtk-update-icon-cache`

**Comment by ammen99** [comment]
I don't think this is a problem with wf-shell, more like a system setup issue since you managed to resolve it without changes to wf-panel. Also recently there were some refactors to icon loading, probably will work this time without crash.
