### ISSUE TITLE
Add option to set menu's icon

### ISSUE THREAD

**Issue by gimpcheesestick** [WayfireWM/wf-shell#24]
Would be nice to have a setting in wf-shell.ini to choose which menu icon you'd like as you're abel to do with the desktop background, right now you can switch the files around and rename them and that works, but if an update is passed your files will be overwritten with the default.

 for example

[menu icon]
.# Full path to image or directory of images
iconimage = /usr/share/icons/gnome/256x256/status/trophy-gold.png

**Comment by soreau** [comment]
@gimpcheesestick Generally speaking, the issue report should remain open until a fix is actually pushed for it.
