### ISSUE TITLE
Add option to set Desktop Background color with Hex #

### ISSUE THREAD

**Issue by gimpcheesestick** [WayfireWM/wf-shell#26]
It would be nice to have the ability to set a solid desktop background color, as you can in the wf-panel,  with a Hex#, wf-background aside.

**Comment by gimpcheesestick** [comment]
I'm unable to tell if somehow my wf-background image is still loaded as it was simply black.jpg, but i did a hard-reboot of the entire system to test and my bg color is still black with above settings in wayfire.ini with 
background_mode=simple
background=0.0 0.0 0.0 1.0

How ever this was the effect I was searching for, one mans bug is another mans tresure. heh

**Comment by ammen99** [comment]
You should get black background if you just don't run wf-background

**Comment by gimpcheesestick** [comment]
It was grey, perhaps at first I was running wf-background with no image set not realizing it and that was causing this effect which i now believe to be the case. I still am however adamant of an option for simple hex bg color in wayfire sans wf-background, so instead of black it could be blue or green or purple or ect, ect. without the need of a wallpaper application process if not desired

**Comment by ammen99** [comment]
This is now part of Wayfire.
See https://github.com/WayfireWM/wayfire/blob/master/wayfire.ini.default#L19 (to get that working, you need to disable wf-background from autostart)

**Comment by scruffidog** [comment]
so how do I disable from autostart ?

these are the only entries in ~/config/wayfire.ini:

[autostart]
autostart_wf_shell = true
idle = swayidle before-sleep swaylock
portal = /usr/libexec/xdg-desktop-portal
redshift = redshift -m wayland

do I delete the [background] section in ~/.config/wf-shell.ini ?

Incidentally, is there a setting for window focus follow input ?

**Comment by soreau** [comment]
@scruffidog Set `autostart_wf_shell = false`

**Comment by soreau** [comment]
you might want to add `panel = wf-panel` to keep the panel

**Comment by scruffidog** [comment]
never mind...Figure out the autostart part. will open separate issue for focus

**Comment by tombh** [comment]
Just want to note that I solve this slightly differently because I don't use `wf-shell` of `wf-panel`. I just simply use the `swaybg` binary and have this is my `[auostart]` section of `wayfire.ini`: `background = swaybg -c '#000000'`
