### ISSUE TITLE
Invalid panel background color in config file

### ISSUE THREAD

**Issue by vdegenne** [WayfireWM/wf-shell#280]
I'm trying to change the panel background color,
I copied the value from  `wf-shell.ini.example` to make sure I'm not doing anything wrong (`background_color = $555555`).
But then upon wf-panel restart I have this error in the logs:

"Invalid panel background color in config file"

Thanks for your help.

**Comment by soreau** [comment]
wf-shell.ini.example is wrong in this case, it should be `\#` instead of `$`.

**Comment by vdegenne** [comment]
Thanks!

Btw I have a very weird output from `wf-panel`, I don't know if I should ignore them, but for now it works.

```
wf-panel
II 30-11-24 12:41:16.220 - [src/file.cpp:579] Reading XML configuration options from directory /usr/share/wayfire/metadata/wf-shell
II 30-11-24 12:41:16.220 - [src/file.cpp:529] Reading XML configuration options from file /usr/share/wayfire/metadata/wf-shell/background.xml
II 30-11-24 12:41:16.220 - [src/file.cpp:529] Reading XML configuration options from file /usr/share/wayfire/metadata/wf-shell/dock.xml
II 30-11-24 12:41:16.220 - [src/file.cpp:529] Reading XML configuration options from file /usr/share/wayfire/metadata/wf-shell/panel.xml
Error loading file:
Error loading file:
Error loading file:
Error loading file:
Error loading file:
Error loading file:
Error loading file:
Error loading file:
Error loading file:
Error loading file:
```

**Comment by soreau** [comment]
Please create a new issue for new questions. Leaving this one open until we fix the example wf-shell config file.

**Comment by vdegenne** [comment]
https://github.com/WayfireWM/wf-shell/pull/281
