### ISSUE TITLE
add status notifier item in wf-panel

### ISSUE THREAD

**Issue by ghost** [WayfireWM/wf-shell#29]
as systemtray is not supported on wayland.
but sni is supposed to be supported.
add the sni widget in wf-panel.

https://freedesktop.org/wiki/Specifications/StatusNotifierItem/

**Comment by ammen99** [comment]
We'll want to eventually add this, but I cannot give any ETA.

FWIW, waybar has such a module: https://github.com/Alexays/Waybar/wiki/Module:-Tray
