### ISSUE TITLE
add leave widget in wf-panel

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wf-shell#30]
add a widget that is able to 
leave- gives all options when clicked
poweroff
logout
lockscreen
reboot
hibernate
suspend
and maybe reboot to uefi firmware.
in the right side of wf-panel

**Comment by shrinivas17081997** [comment]
https://github.com/ArtsyMacaw/wlogout

okay its close
just have to use
killall wayfire
or 
pkill -u $USER
 in logout command
