### ISSUE TITLE
provide a default background

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wf-shell#31]
add a background picture in the package 
so it will be installed with the
wf-shell.
and as the path will be /usr/.... it wont change with any distro or user
and in the wf-shell.ini config set this background as default.
so that users wont be presented an black screen and assume wf-shell is not working.
it happened with me as panel did not launch and i was presented black screen.

**Comment by erikvanhamme** [comment]
I am heavily into photography and I would be more than happy to donate images as a default background. Ask and ye shall receive.

**Comment by erikvanhamme** [comment]
As discussed in the IRC channel, here is the desktop image:

![wayfire_desktop_4k](https://user-images.githubusercontent.com/12248753/76710336-07b5ac00-6707-11ea-95c9-1c6388a5e7b2.jpg)

**Comment by ammen99** [comment]
Fixed in d918c8951ffcbd96517498533012c85d4ec7bc9

**Comment by ammen99** [comment]
btw thanks @erikvanhamme :)
