### ISSUE TITLE
questions regarding wayfire session

### ISSUE THREAD

**Issue by librewish** [WayfireWM/wf-shell#32]
1. how to configure the monitors?
resolution.
primary and secondary monitor.
extend monitor.

2.screen off timing.
presentation mode.
lockscreen timing.

3.which policykit package do you suggest to use.
currently im using lxqt-policykit-agent.
and have set it to autostart.

**Comment by librewish** [comment]
okay after some searching around i myself found answer to the question
graphical output managers.
1.wlay 
https://github.com/atx/wlay

2.kanshi
https://github.com/emersion/kanshi

3.wlr-randr
https://github.com/emersion/wlr-randr

**Comment by ammen99** [comment]
For 1 and 2, you can also check https://github.com/WayfireWM/wayfire.org/blob/wayfire-0.3-tile/_posts/Wayfire03.md, the blog post is WIP but I have described some of the options you'll need.

For lockscreen, currently the only option is using swayidle + swaylock, so it isn't something that is controlled by Wayfire.

For 3, I am not sure what this is so I can't really help :(
