### ISSUE TITLE
Release tag for wf-shell 0.3 contains tarballs for wayfire

### ISSUE THREAD

**Issue by aperezdc** [WayfireWM/wf-shell#33]
The release files for the [wf-shell 0.3 tag](https://github.com/WayfireWM/wf-shell/releases/tag/0.3) have attached files `wayfire-0.3.tar.xz` and `wayfire-0.3.tar.xz.sha256sums`. The contents of the tarball do not seem to include wf-shell.

**Comment by ammen99** [comment]
Oh yes, you're right, thanks for the heads up! I uploaded the correct archives.

**Comment by aperezdc** [comment]
@ammen99 Thanks a lot for the quick fix! :smile:
