### ISSUE TITLE
Segfault in wf-background if there is no valid desktop image selected

### ISSUE THREAD

**Issue by erikvanhamme** [WayfireWM/wf-shell#47]
Can be reproduced by setting an incorrect image or path in the wf-shell.ini file.

**Comment by ammen99** [comment]
I cannot reproduce. Can you run in gdb and post a backtrace?

**Comment by erikvanhamme** [comment]
Re-verified it, and the crash happens when the image = tag is missing. Not when it is incorrect.

This is what I had in my wf-shell.ini.
`
[background]
# Full path to image or directory of images
#image = /home/rsq/Pictures/wallpapers
# Whether to scale images or preserve background ratio
#preserve_aspect = 0
# In the case of directory, timeout between changing backgrounds, in seconds
#cycle_timeout = 150
# In the case of directory, whether or not to randomize images
#randomize = 0

# configuration for the panel
[panel]
`
