### ISSUE TITLE
Fails to build with libc++

### ISSUE THREAD

**Issue by jbeich** [WayfireWM/wf-shell#49]
libc++ forbids using `std::random_shuffle(first, last)` in C++17 or later unless `_LIBCPP_ENABLE_CXX17_REMOVED_RANDOM_SHUFFLE` is defined.
See also https://en.cppreference.com/w/cpp/algorithm/random_shuffle
```c++
../src/background/background.cpp:150:14: error: no member named 'random_shuffle' in namespace 'std'
        std::random_shuffle(images.begin(), images.end());
        ~~~~~^
```

**Comment by ammen99** [comment]
Indeed, thanks for the heads-up.
