### ISSUE TITLE
[query] Network plugin - custom launch command

### ISSUE THREAD

**Issue by psstoyanov** [WayfireWM/wf-shell#55]
Is it possible to allow for override/ custom launch command when you click on the network?

`nm-connection-editor` works good as an alternative and wouldn't require gnome control center (which usually comes with a lot of dependencies).
 
It would be interesting if the commands could be customized or changed for the `on_click` event

**Comment by ammen99** [comment]
Hmm, I can imagine this being useful, PRs welcome.

**Comment by psstoyanov** [comment]
Is the [gitter channel](https://gitter.im/Wayfire-WM/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) the best place to have a discussion?

This will be entirely new to me

**Comment by soreau** [comment]
@psstoyanov We use #wayfire on irc.freenode.net primarily

**Comment by jgmdev** [comment]
I added the small change to support this on pull #81 without noticing there was an issue requesting this, so commenting here to reference it.

**Comment by ammen99** [comment]
Fixed in #81

**Comment by starsareintherose** [comment]
sorry, do I need to use 
```
network_onclick_command = tilix -e 'nmtui'
```
to specific? if so, it doesn't work for me.
