### ISSUE TITLE
Allow to specify config file on command line [Feature Request]

### ISSUE THREAD

**Issue by VaZark** [WayfireWM/wf-shell#57]
**Use Case:** Running multiple panels. (I'm trying to set up a wayfire-based environment for the pinephone)

**Issue:** Since all instances of the panel refer to the same config file, we get two consecutive panels and any changes to config is followed by both instances

_Proposed Solution:_ Add an additional param `--config /path/to/config` to support different config files at program start

**Comment by ammen99** [comment]
I know a long time has passed, but I just implemented this option, you can use `-c` or `--config` to specify custom config files to all wf-shell clients (panel, dock, background).
