### ISSUE TITLE
[window-list] Can't set colors

### ISSUE THREAD

**Issue by nwg-piotr** [WayfireWM/wf-shell#64]
I have no idea on how to change background and font colors. Regardless of how I set the background_color (`background_color = gtk_headerbar` or an rgb value), the background color does not change. Also I can't figure out how to change the font color. In result inactive windows on the list are represented by dark grey text on dark grey background.

Same applies to the dock.

Am I doing anything wrong? 

![image](https://user-images.githubusercontent.com/20579136/93006211-b709f900-f559-11ea-881d-41067782108c.png)

**Comment by soreau** [comment]
The colors are ultimately controlled by the gtk theme.

**Comment by nwg-piotr** [comment]
Well, changing themes does not affect neither the panel nor the dock on my machine. :(

**Comment by soreau** [comment]
Changing the theme may be different depending on your distro. Here, I have to set e.g. `GTK_THEME=Greybird:dark`

**Comment by nwg-piotr** [comment]
This works for me in all windows, but not in the panel nor dock.

**Comment by nwg-piotr** [comment]
Wait! You meant an environment variable?

**Comment by nwg-piotr** [comment]
This seems to work.

**Comment by ammen99** [comment]
I do not think we can do much. Wf-panel never overrides colors except for the background optuon, if it is set (i.e we use gtk defaults, not sure why it picks the wrong theme)

**Comment by nwg-piotr** [comment]
Well, I just wanted the panel to show me `window-list`, but I can live without it. As I'm addicted to having a lot of info in my panels, for now I'll stick to waybar.

**Comment by ammen99** [comment]
@nwg-piotr If you use waybar, it also has a window-list-like module which works on Wayfire. I do not remember how it is called, something with `wlr/`

**Comment by nwg-piotr** [comment]
Brilliant, thank you! On sway I use `sway/workspaces` and a script to rename them after the last focused window name.

The `wlr/taskbar` module works excellent on Wayfire, apart from a minor issue w/ the `minimize` action.

![image](https://user-images.githubusercontent.com/20579136/93031010-c48db480-f627-11ea-935a-35dde71ef3ce.png)

By the way: do we have any equivalent to the sway `reload` command on Wayfire?

**Comment by soreau** [comment]
Can you say what you expect sway reload to do? All changes to wayfire.ini should be applied upon saving the file, except a few cases such as vwidth/vheight options, which require wayfire restart.

**Comment by nwg-piotr** [comment]
Actually I only need to restart waybar. For some reason I can't kill it and start again on the fly.

**Comment by soreau** [comment]
What happens when you try?

**Comment by nwg-piotr** [comment]
If I execute a script like this from terminal, it works:

```bash
pkill -f waybar
exec waybar
```
 The same called from a key binding:

```bash
binding_rwaybar = <super> <shift> KEY_C
command_rwaybar = /home/piotr/.local/bin/restart_waybar.sh
```

kills waybar, but does not start it again.

**Comment by soreau** [comment]
the commands are run with sh, try without exec maybe?

**Comment by nwg-piotr** [comment]
Still the same effect.

**Comment by soreau** [comment]
Are you sure `/home/piotr/.local/bin/restart_waybar.sh` is executable? The other thing it might be is that you need a `sleep 0.5` or so in between killing and starting waybar.

**Comment by nwg-piotr** [comment]
It is, as it kills waybar. I tried adding sleep with no effect. :/

**Comment by nwg-piotr** [comment]
And `[piotr@msi ~]$ /home/piotr/.local/bin/restart_waybar.sh` from terminal works as expected.

**Comment by soreau** [comment]
Well it's calling `/bin/sh -c /home/piotr/.local/bin/restart_waybar.sh` internally.
Here's a couple more things to try:

- Pipe the output of waybar to file and see if it outputs anything when it doesn't start
- Print the environment in the script called by wayfire and compare it with the environment in your terminal

**Comment by nwg-piotr** [comment]
After the `pkill -f waybar` nothing else is executed, **if I run the script from the key binding**.

```bash
echo "Hello" > waybar.txt
pkill -f waybar
echo " there!" > waybar.txt
waybar -c /home/piotr/.config/waybar/config-wayfire >> waybar.txt
```

only saves "hello" to the `waybar.txt` file.

**Comment by nwg-piotr** [comment]
`killall -9 waybar` seems to work as it should.
