### ISSUE TITLE
Scrollbars on window-list with weird characters

### ISSUE THREAD

**Issue by wb9688** [WayfireWM/wf-shell#68]
Having scrollbars on `window-list` in `wf-panel` when a title contains weird unicode characters, window-list get scrollbars, which looks weird. https://soundcloud.com/thatrickaz is an example of a website with such characters in its title.

**Comment by soreau** [comment]
The only reason a scrollbar will appear is if there are too many views in the list, if I remember correctly. It shouldn't have anything to do with the characters in the title though perhaps the title length might affect it.

**Comment by wb9688** [comment]
@soreau: No, look: 
![thatrickaz](https://user-images.githubusercontent.com/46277131/96280499-55b1cb80-0fd8-11eb-9fba-0deffb516181.png)

**Comment by soreau** [comment]
The size of the window-list widget appears to be constrained. There is code that does this and I'm not sure how reliable it is. You might try GTK_DEBUG=interactive and see what size it gets.

**Comment by soreau** [comment]
This is because you are trying to use a font size that is too big for your panel size.

**Comment by wb9688** [comment]
How is my font too big when it doesn't happen for normal characters?

**Comment by soreau** [comment]
For example, if you use a smaller font size such as 11 or less, it will not happen. Perhaps it is a gtk bug that the widget size changes when displaying a label containing unicode characters.
