### ISSUE TITLE
Provide a sample config file and a README

### ISSUE THREAD

**Issue by ammen99** [WayfireWM/wf-shell#7]
- [x] Example config

- [ ] Man/Wiki page describing options

- [x] Screenshots

- [x] Build instructions

**Comment by NamorNiradnug** [comment]
Hi. I've written something on the wiki pages, it's not completed yet, but I will finish that shortly. Could you please review it and close this issue?

**Comment by ammen99** [comment]
The wiki seems great so far :) You  might want to upload a newer screenshot on the main page, I have the feeling a screenshot of your desktop will look nicer than mine :) I have very little styling so it looks like a random jumble of things.
