### ISSUE TITLE
Position panel at the bottom?

### ISSUE THREAD

**Issue by varmanishant** [WayfireWM/wf-shell#9]
How can I change the position of the panel to bottom?

**Comment by ammen99** [comment]
Currently isn't implemented, but should be trivial to add. I'll try to do that in the next few days.

**Comment by ammen99** [comment]
@varmanishant Actually just looked into it, and added it. You need the latest commit 4c4d42cf3c8e999f413ade4335c8cecf7daae357. In the config file for wf-shell, just set `position = bottom` in the panel section.

**Comment by varmanishant** [comment]
Thanks a lot @ammen99 for the prompt response! It works fine.
