### ISSUE TITLE
[request] support autohide feature in waybar

### ISSUE THREAD

**Issue by gitpubber** [WayfireWM/wf-shell#90]
I know  that this is not place to ask but wf-shell's panel is not upto mark as Waybar's . 

I also asked at Waybar's issue but it is being ignored. 

I also know that autohide uses wayfire-shell-unstable-v2.xml and not standardized in Wayland.

So, how can autohide be achieved in Waybar ?

**Comment by ammen99** [comment]
Waybar can just adjust its margin so that it is hidden, leaving just one pixel visible at the edge of the screen.

Or, it can have a wayfire-specific module which utilizes wayfire-shell-unstable but that won't work on e.g. sway.
