### ISSUE TITLE
everything takes a looong time to start

### ISSUE THREAD

**Issue by MrSwedish** [WayfireWM/wf-shell#94]
since i uninstalled pipewire, everything takes so long, audio works everywhere
but could you please fix this?

**Comment by soreau** [comment]
Does [this](https://github.com/WayfireWM/wayfire/issues/775#issuecomment-706430208) help?

**Comment by MrSwedish** [comment]
sadly no

**Comment by soreau** [comment]
well you can join us on #wayfire on Libera chat or Matrix and we can try to help you further.

**Comment by MrSwedish** [comment]
alright
how do I, I have a matrix client

**Comment by MrSwedish** [comment]
alright i think i'm there

**Comment by MrSwedish** [comment]
i just have to install pipewire for some reason
